/**
 * NIST Statistical Test Suite for Entropy Quality Validation
 * 
 * Implements a subset of the NIST SP 800-22 randomness tests to validate
 * the quality of entropy generated by the three-body physics simulation.
 * 
 * Tests implemented:
 * 1. Frequency (Monobit) Test - Tests if the number of 1s and 0s are approximately equal
 * 2. Runs Test - Tests if the oscillation between 0s and 1s is too fast or too slow
 * 3. Chi-Square Test - Tests if the distribution is uniform
 * 4. Entropy Estimation - Estimates the Shannon entropy of the data
 * 
 * @module nist-tests
 */

/**
 * Result of a single NIST test
 */
export interface NISTTestResult {
  testName: string;
  passed: boolean;
  pValue: number;
  statistic: number;
  details: string;
}

/**
 * Combined result of all NIST tests
 */
export interface NISTTestSuiteResult {
  passed: boolean;
  pValue: number;
  tests: NISTTestResult[];
  sampleCount: number;
  totalBits: number;
  timestamp: number;
}

/**
 * Chi-square test result
 */
export interface ChiSquareResult {
  passed: boolean;
  pValue: number;
  chiSquareStatistic: number;
  degreesOfFreedom: number;
  observed: number[];
  expected: number[];
}

/**
 * Entropy estimation result
 */
export interface EntropyEstimationResult {
  shannonEntropy: number;
  maxEntropy: number;
  entropyRatio: number;
  passed: boolean;
}

/**
 * Converts a hex string to a binary string
 */
function hexToBinary(hex: string): string {
  return hex
    .split('')
    .map(char => parseInt(char, 16).toString(2).padStart(4, '0'))
    .join('');
}

/**
 * Calculates the complementary error function (erfc)
 * Used for p-value calculations in NIST tests
 */
function erfc(x: number): number {
  const a1 = 0.254829592;
  const a2 = -0.284496736;
  const a3 = 1.421413741;
  const a4 = -1.453152027;
  const a5 = 1.061405429;
  const p = 0.3275911;

  const sign = x < 0 ? -1 : 1;
  x = Math.abs(x);

  const t = 1.0 / (1.0 + p * x);
  const y = 1.0 - (((((a5 * t + a4) * t) + a3) * t + a2) * t + a1) * t * Math.exp(-x * x);

  return 1 - sign * y;
}

/**
 * Calculates the incomplete gamma function P(a, x)
 * Used for chi-square p-value calculation
 */
function gammainc(a: number, x: number): number {
  if (x < 0 || a <= 0) {
    return 0;
  }

  if (x === 0) {
    return 0;
  }

  // Use series expansion for small x
  if (x < a + 1) {
    let sum = 1 / a;
    let term = 1 / a;
    for (let n = 1; n < 100; n++) {
      term *= x / (a + n);
      sum += term;
      if (Math.abs(term) < 1e-10 * Math.abs(sum)) {
        break;
      }
    }
    return sum * Math.exp(-x + a * Math.log(x) - lgamma(a));
  }

  // Use continued fraction for large x
  let f = 1e-30;
  let c = 1e-30;
  let d = 0;

  for (let i = 1; i <= 100; i++) {
    const an = -i * (i - a);
    const bn = x + 2 * i + 1 - a;
    d = bn + an * d;
    if (Math.abs(d) < 1e-30) d = 1e-30;
    c = bn + an / c;
    if (Math.abs(c) < 1e-30) c = 1e-30;
    d = 1 / d;
    const del = d * c;
    f *= del;
    if (Math.abs(del - 1) < 1e-10) {
      break;
    }
  }

  return 1 - f * Math.exp(-x + a * Math.log(x) - lgamma(a));
}

/**
 * Log gamma function approximation (Lanczos approximation)
 */
function lgamma(x: number): number {
  const g = 7;
  const c = [
    0.99999999999980993,
    676.5203681218851,
    -1259.1392167224028,
    771.32342877765313,
    -176.61502916214059,
    12.507343278686905,
    -0.13857109526572012,
    9.9843695780195716e-6,
    1.5056327351493116e-7
  ];

  if (x < 0.5) {
    return Math.log(Math.PI / Math.sin(Math.PI * x)) - lgamma(1 - x);
  }

  x -= 1;
  let a = c[0];
  const t = x + g + 0.5;

  for (let i = 1; i < g + 2; i++) {
    a += c[i] / (x + i);
  }

  return 0.5 * Math.log(2 * Math.PI) + (x + 0.5) * Math.log(t) - t + Math.log(a);
}

/**
 * Chi-square cumulative distribution function
 */
function chiSquareCDF(x: number, k: number): number {
  return gammainc(k / 2, x / 2);
}

/**
 * Frequency (Monobit) Test
 * 
 * Tests the proportion of ones in the entire sequence.
 * The purpose is to determine whether the number of ones and zeros
 * in a sequence are approximately the same as would be expected
 * for a truly random sequence.
 * 
 * @param binaryString - Binary string to test
 * @returns Test result with p-value
 */
export function frequencyTest(binaryString: string): NISTTestResult {
  const n = binaryString.length;
  
  if (n < 100) {
    return {
      testName: 'Frequency (Monobit) Test',
      passed: false,
      pValue: 0,
      statistic: 0,
      details: `Insufficient data: ${n} bits (minimum 100 required)`
    };
  }

  // Count ones and calculate S_n
  let sum = 0;
  for (const bit of binaryString) {
    sum += bit === '1' ? 1 : -1;
  }

  // Calculate test statistic
  const sObs = Math.abs(sum) / Math.sqrt(n);
  
  // Calculate p-value using complementary error function
  const pValue = erfc(sObs / Math.sqrt(2));

  return {
    testName: 'Frequency (Monobit) Test',
    passed: pValue >= 0.01,
    pValue,
    statistic: sObs,
    details: `S_n = ${sum}, S_obs = ${sObs.toFixed(6)}, n = ${n}`
  };
}

/**
 * Runs Test
 * 
 * Tests the total number of runs in the sequence, where a run is an
 * uninterrupted sequence of identical bits. The purpose is to determine
 * whether the oscillation between zeros and ones is too fast or too slow.
 * 
 * @param binaryString - Binary string to test
 * @returns Test result with p-value
 */
export function runsTest(binaryString: string): NISTTestResult {
  const n = binaryString.length;

  if (n < 100) {
    return {
      testName: 'Runs Test',
      passed: false,
      pValue: 0,
      statistic: 0,
      details: `Insufficient data: ${n} bits (minimum 100 required)`
    };
  }

  // Calculate proportion of ones
  let ones = 0;
  for (const bit of binaryString) {
    if (bit === '1') ones++;
  }
  const pi = ones / n;

  // Pre-test: Check if frequency test would pass
  const tau = 2 / Math.sqrt(n);
  if (Math.abs(pi - 0.5) >= tau) {
    return {
      testName: 'Runs Test',
      passed: false,
      pValue: 0,
      statistic: 0,
      details: `Pre-test failed: pi = ${pi.toFixed(6)}, tau = ${tau.toFixed(6)}`
    };
  }

  // Count runs
  let runs = 1;
  for (let i = 1; i < n; i++) {
    if (binaryString[i] !== binaryString[i - 1]) {
      runs++;
    }
  }

  // Calculate test statistic
  const expectedRuns = 2 * n * pi * (1 - pi);
  const variance = 2 * n * pi * (1 - pi);
  const statistic = Math.abs(runs - expectedRuns) / Math.sqrt(2 * variance);

  // Calculate p-value
  const pValue = erfc(statistic);

  return {
    testName: 'Runs Test',
    passed: pValue >= 0.01,
    pValue,
    statistic,
    details: `Runs = ${runs}, Expected = ${expectedRuns.toFixed(2)}, pi = ${pi.toFixed(6)}`
  };
}

/**
 * Chi-Square Test for Uniform Distribution
 * 
 * Tests whether the distribution of values is uniform across buckets.
 * Used to verify that entropy values are uniformly distributed.
 * 
 * @param samples - Array of numeric samples (should be normalized 0-1 or integers)
 * @param numBuckets - Number of buckets for the histogram (default: 256 for byte values)
 * @returns Chi-square test result
 */
export function chiSquareTest(samples: number[], numBuckets: number = 256): ChiSquareResult {
  const n = samples.length;
  
  if (n < numBuckets) {
    return {
      passed: false,
      pValue: 0,
      chiSquareStatistic: 0,
      degreesOfFreedom: numBuckets - 1,
      observed: [],
      expected: [],
    };
  }

  // Determine if samples are normalized (0-1) or integer values
  const maxSample = Math.max(...samples);
  const isNormalized = maxSample <= 1;

  // Create histogram
  const observed: number[] = new Array(numBuckets).fill(0);
  
  for (const sample of samples) {
    let bucket: number;
    if (isNormalized) {
      bucket = Math.min(Math.floor(sample * numBuckets), numBuckets - 1);
    } else {
      bucket = Math.min(Math.floor(sample) % numBuckets, numBuckets - 1);
    }
    observed[bucket]++;
  }

  // Expected count per bucket for uniform distribution
  const expectedCount = n / numBuckets;
  const expected: number[] = new Array(numBuckets).fill(expectedCount);

  // Calculate chi-square statistic
  let chiSquare = 0;
  for (let i = 0; i < numBuckets; i++) {
    const diff = observed[i] - expected[i];
    chiSquare += (diff * diff) / expected[i];
  }

  // Degrees of freedom
  const df = numBuckets - 1;

  // Calculate p-value (1 - CDF)
  const pValue = 1 - chiSquareCDF(chiSquare, df);

  return {
    passed: pValue >= 0.01,
    pValue,
    chiSquareStatistic: chiSquare,
    degreesOfFreedom: df,
    observed,
    expected,
  };
}

/**
 * Shannon Entropy Estimation
 * 
 * Estimates the Shannon entropy of the data to measure randomness.
 * Maximum entropy for n bits is log2(n), and for uniform distribution
 * over k symbols is log2(k).
 * 
 * @param samples - Array of numeric samples or hex strings
 * @param symbolSize - Size of symbols in bits (default: 8 for bytes)
 * @returns Entropy estimation result
 */
export function estimateEntropy(samples: (number | string)[], symbolSize: number = 8): EntropyEstimationResult {
  const numSymbols = Math.pow(2, symbolSize);
  const counts: Map<number, number> = new Map();
  let totalSymbols = 0;

  for (const sample of samples) {
    let value: number;
    if (typeof sample === 'string') {
      // Convert hex string to number (use first symbolSize bits)
      value = parseInt(sample.slice(0, Math.ceil(symbolSize / 4)), 16) % numSymbols;
    } else {
      value = Math.floor(sample) % numSymbols;
    }
    
    counts.set(value, (counts.get(value) || 0) + 1);
    totalSymbols++;
  }

  // Calculate Shannon entropy
  let entropy = 0;
  for (const count of counts.values()) {
    if (count > 0) {
      const p = count / totalSymbols;
      entropy -= p * Math.log2(p);
    }
  }

  // Maximum entropy for uniform distribution
  const maxEntropy = Math.log2(numSymbols);
  const entropyRatio = entropy / maxEntropy;

  // Pass if entropy is at least 95% of maximum
  const passed = entropyRatio >= 0.95;

  return {
    shannonEntropy: entropy,
    maxEntropy,
    entropyRatio,
    passed,
  };
}

/**
 * Runs all NIST tests on a collection of entropy samples
 * 
 * @param samples - Array of hex strings representing entropy values
 * @param significanceLevel - P-value threshold for passing (default: 0.01 for 99% confidence)
 * @returns Combined test suite result
 */
export function runNISTTests(samples: string[], significanceLevel: number = 0.01): NISTTestSuiteResult {
  // Concatenate all hex samples into a single binary string
  const binaryString = samples.map(hexToBinary).join('');
  const totalBits = binaryString.length;

  // Run individual tests
  const frequencyResult = frequencyTest(binaryString);
  const runsResult = runsTest(binaryString);

  // For chi-square, convert hex samples to numeric values
  const numericSamples = samples.map(hex => parseInt(hex.slice(0, 8), 16) / 0xFFFFFFFF);
  const chiSquareResult = chiSquareTest(numericSamples, 16); // Use 16 buckets for better statistics

  // Estimate entropy
  const entropyResult = estimateEntropy(samples);

  // Create test results array
  const tests: NISTTestResult[] = [
    frequencyResult,
    runsResult,
    {
      testName: 'Chi-Square Test',
      passed: chiSquareResult.passed,
      pValue: chiSquareResult.pValue,
      statistic: chiSquareResult.chiSquareStatistic,
      details: `Chi-square = ${chiSquareResult.chiSquareStatistic.toFixed(4)}, df = ${chiSquareResult.degreesOfFreedom}`
    },
    {
      testName: 'Entropy Estimation',
      passed: entropyResult.passed,
      pValue: entropyResult.entropyRatio, // Use ratio as pseudo p-value
      statistic: entropyResult.shannonEntropy,
      details: `Shannon entropy = ${entropyResult.shannonEntropy.toFixed(4)} bits, ratio = ${(entropyResult.entropyRatio * 100).toFixed(2)}%`
    }
  ];

  // Calculate overall result
  const allPassed = tests.every(t => t.passed);
  
  // Use minimum p-value as overall p-value (conservative approach)
  const minPValue = Math.min(
    frequencyResult.pValue,
    runsResult.pValue,
    chiSquareResult.pValue
  );

  return {
    passed: allPassed,
    pValue: minPValue,
    tests,
    sampleCount: samples.length,
    totalBits,
    timestamp: Date.now()
  };
}

/**
 * Calculates chi-square statistic for a set of numeric samples
 * Convenience function for direct use in tests
 * 
 * @param samples - Array of numeric samples
 * @param numBuckets - Number of buckets (default: 16)
 * @returns Object with pValue and chiSquare statistic
 */
export function calculateChiSquare(samples: number[], numBuckets: number = 16): { pValue: number; chiSquare: number } {
  const result = chiSquareTest(samples, numBuckets);
  return {
    pValue: result.pValue,
    chiSquare: result.chiSquareStatistic
  };
}
