/**
 * Entropy Quality Assurance Tests
 * 
 * Validates the quality of entropy generated by the three-body physics simulation
 * using NIST SP 800-22 statistical tests and other randomness metrics.
 * 
 * These tests ensure that the entropy oracle produces cryptographically suitable
 * random values for provably fair gaming applications.
 * 
 * @module entropy-quality-tests
 */

import { describe, it, expect, beforeAll } from 'vitest';
import { 
  runNISTTests, 
  calculateChiSquare, 
  frequencyTest, 
  runsTest, 
  chiSquareTest,
  estimateEntropy,
  type NISTTestSuiteResult 
} from './utils/nist-tests';
import type { RawEntropyResult } from '../../modules/shared-types/src';
import { runSimulation, generateRandomConditions } from '../../modules/entropy-oracle/src/simulation';

/**
 * Generates entropy samples from the physics simulation
 */
async function generateEntropySamples(count: number): Promise<RawEntropyResult[]> {
  const samples: RawEntropyResult[] = [];
  
  for (let i = 0; i < count; i++) {
    const conditions = generateRandomConditions(`seed-${i}-${Date.now()}`);
    const entropy = runSimulation(
      { duration: 5.0, timeStep: 0.001 },
      conditions
    );
    samples.push(entropy);
  }
  
  return samples;
}

/**
 * Converts entropy samples to hex strings for NIST tests
 */
function samplesToHexStrings(samples: RawEntropyResult[]): string[] {
  return samples.map(s => s.hex);
}

/**
 * Converts entropy samples to numeric values for chi-square tests
 */
function samplesToNumericValues(samples: RawEntropyResult[]): number[] {
  return samples.map(s => parseInt(s.hex.slice(0, 8), 16));
}

describe('Entropy Quality Assurance', () => {
  let entropySamples: RawEntropyResult[];
  let hexStrings: string[];
  let numericValues: number[];

  beforeAll(async () => {
    console.log('Generating 1000 entropy samples for statistical testing...');
    entropySamples = await generateEntropySamples(1000);
    hexStrings = samplesToHexStrings(entropySamples);
    numericValues = samplesToNumericValues(entropySamples);
    console.log(`Generated ${entropySamples.length} samples`);
  }, 300000); // 5 minute timeout for sample generation

  describe('NIST Randomness Tests', () => {
    it('passes NIST randomness test suite', () => {
      const results: NISTTestSuiteResult = runNISTTests(hexStrings);
      
      console.log('\nNIST Test Suite Results:');
      console.log(`Overall passed: ${results.passed}`);
      console.log(`Overall p-value: ${results.pValue.toFixed(6)}`);
      console.log(`Sample count: ${results.sampleCount}`);
      console.log(`Total bits analyzed: ${results.totalBits}`);
      
      for (const test of results.tests) {
        console.log(`\n${test.testName}:`);
        console.log(`  Passed: ${test.passed}`);
        console.log(`  P-value: ${test.pValue.toFixed(6)}`);
        console.log(`  Statistic: ${test.statistic.toFixed(6)}`);
        console.log(`  Details: ${test.details}`);
      }

      expect(results.passed).toBe(true);
      expect(results.pValue).toBeGreaterThan(0.01);
    });

    it('passes frequency (monobit) test individually', () => {
      const binaryString = hexStrings
        .map(hex => hex.split('').map(c => parseInt(c, 16).toString(2).padStart(4, '0')).join(''))
        .join('');
      
      const result = frequencyTest(binaryString);
      
      console.log('\nFrequency Test Results:');
      console.log(`  Passed: ${result.passed}`);
      console.log(`  P-value: ${result.pValue.toFixed(6)}`);
      console.log(`  Details: ${result.details}`);

      expect(result.passed).toBe(true);
      expect(result.pValue).toBeGreaterThan(0.01);
    });

    it('passes runs test individually', () => {
      const binaryString = hexStrings
        .map(hex => hex.split('').map(c => parseInt(c, 16).toString(2).padStart(4, '0')).join(''))
        .join('');
      
      const result = runsTest(binaryString);
      
      console.log('\nRuns Test Results:');
      console.log(`  Passed: ${result.passed}`);
      console.log(`  P-value: ${result.pValue.toFixed(6)}`);
      console.log(`  Details: ${result.details}`);

      expect(result.passed).toBe(true);
      expect(result.pValue).toBeGreaterThan(0.01);
    });
  });

  describe('Uniform Distribution Tests', () => {
    it('has uniform distribution (chi-square test)', () => {
      const chiSquare = calculateChiSquare(numericValues, 16);
      
      console.log('\nChi-Square Test Results:');
      console.log(`  P-value: ${chiSquare.pValue.toFixed(6)}`);
      console.log(`  Chi-square statistic: ${chiSquare.chiSquare.toFixed(4)}`);

      expect(chiSquare.pValue).toBeGreaterThan(0.01);
    });

    it('has uniform byte distribution', () => {
      const byteValues = hexStrings.map(hex => parseInt(hex.slice(0, 2), 16));
      const result = chiSquareTest(byteValues, 256);
      
      console.log('\nByte Distribution Test Results:');
      console.log(`  Passed: ${result.passed}`);
      console.log(`  P-value: ${result.pValue.toFixed(6)}`);
      console.log(`  Chi-square: ${result.chiSquareStatistic.toFixed(4)}`);
      console.log(`  Degrees of freedom: ${result.degreesOfFreedom}`);

      expect(result.pValue).toBeGreaterThan(0.01);
    });

    it('has uniform nibble distribution', () => {
      const nibbleValues: number[] = [];
      for (const hex of hexStrings) {
        for (const char of hex.slice(0, 16)) {
          nibbleValues.push(parseInt(char, 16));
        }
      }
      
      const result = chiSquareTest(nibbleValues, 16);
      
      console.log('\nNibble Distribution Test Results:');
      console.log(`  Passed: ${result.passed}`);
      console.log(`  P-value: ${result.pValue.toFixed(6)}`);
      console.log(`  Chi-square: ${result.chiSquareStatistic.toFixed(4)}`);

      expect(result.pValue).toBeGreaterThan(0.01);
    });
  });

  describe('Entropy Estimation', () => {
    it('has high Shannon entropy', () => {
      const result = estimateEntropy(hexStrings);
      
      console.log('\nEntropy Estimation Results:');
      console.log(`  Shannon entropy: ${result.shannonEntropy.toFixed(4)} bits`);
      console.log(`  Maximum entropy: ${result.maxEntropy.toFixed(4)} bits`);
      console.log(`  Entropy ratio: ${(result.entropyRatio * 100).toFixed(2)}%`);
      console.log(`  Passed (>= 95%): ${result.passed}`);

      expect(result.passed).toBe(true);
      expect(result.entropyRatio).toBeGreaterThanOrEqual(0.95);
    });

    it('entropy increases with sample size', () => {
      const sizes = [100, 250, 500, 1000];
      const ratios: number[] = [];
      
      console.log('\nEntropy vs Sample Size:');
      for (const size of sizes) {
        const subset = hexStrings.slice(0, size);
        const result = estimateEntropy(subset);
        ratios.push(result.entropyRatio);
        console.log(`  ${size} samples: ${(result.entropyRatio * 100).toFixed(2)}% entropy ratio`);
      }
      
      // Verify entropy generally increases with sample size (allowing small variance)
      // Small samples have inherent bias in entropy estimation, so we only check trend
      for (let i = 1; i < ratios.length; i++) {
        // Allow up to 5% decrease due to statistical variance
        expect(ratios[i]).toBeGreaterThanOrEqual(ratios[i - 1] - 0.05);
      }
      
      // The full 1000 sample set should have high entropy (>= 95%)
      expect(ratios[ratios.length - 1]).toBeGreaterThanOrEqual(0.95);
    });
  });

  describe('Entropy Value Properties', () => {
    it('produces unique entropy values', () => {
      const uniqueHashes = new Set(hexStrings);
      const uniquenessRatio = uniqueHashes.size / hexStrings.length;
      
      console.log('\nUniqueness Test:');
      console.log(`  Total samples: ${hexStrings.length}`);
      console.log(`  Unique hashes: ${uniqueHashes.size}`);
      console.log(`  Uniqueness ratio: ${(uniquenessRatio * 100).toFixed(2)}%`);

      expect(uniquenessRatio).toBe(1.0);
    });

    it('produces valid hex strings', () => {
      const hexPattern = /^[0-9a-f]{64}$/;
      
      for (const hex of hexStrings) {
        expect(hex).toMatch(hexPattern);
      }
    });

    it('produces entropy values in valid range', () => {
      for (const sample of entropySamples) {
        expect(sample.value).toBeGreaterThanOrEqual(0);
        expect(sample.value).toBeLessThan(1);
      }
    });

    it('includes valid simulation metadata', () => {
      for (const sample of entropySamples) {
        expect(sample.metadata).toBeDefined();
        expect(sample.metadata.duration).toBeGreaterThan(0);
        expect(sample.metadata.timeStep).toBeGreaterThan(0);
        expect(sample.metadata.steps).toBeGreaterThan(0);
        expect(typeof sample.metadata.finalEnergy).toBe('number');
        expect(typeof sample.metadata.energyDrift).toBe('number');
        expect(typeof sample.metadata.lyapunovEstimate).toBe('number');
      }
    });
  });

  describe('Statistical Independence', () => {
    it('shows no correlation between consecutive samples', () => {
      let correlation = 0;
      const n = numericValues.length - 1;
      
      const mean = numericValues.reduce((a, b) => a + b, 0) / numericValues.length;
      const variance = numericValues.reduce((a, b) => a + (b - mean) ** 2, 0) / numericValues.length;
      const stdDev = Math.sqrt(variance);
      
      for (let i = 0; i < n; i++) {
        const x = (numericValues[i] - mean) / stdDev;
        const y = (numericValues[i + 1] - mean) / stdDev;
        correlation += x * y;
      }
      correlation /= n;
      
      console.log('\nSerial Correlation Test:');
      console.log(`  Correlation coefficient: ${correlation.toFixed(6)}`);
      console.log(`  Expected (random): ~0`);

      expect(Math.abs(correlation)).toBeLessThan(0.1);
    });

    it('shows no correlation with lag-2 samples', () => {
      let correlation = 0;
      const n = numericValues.length - 2;
      
      const mean = numericValues.reduce((a, b) => a + b, 0) / numericValues.length;
      const variance = numericValues.reduce((a, b) => a + (b - mean) ** 2, 0) / numericValues.length;
      const stdDev = Math.sqrt(variance);
      
      for (let i = 0; i < n; i++) {
        const x = (numericValues[i] - mean) / stdDev;
        const y = (numericValues[i + 2] - mean) / stdDev;
        correlation += x * y;
      }
      correlation /= n;
      
      console.log('\nLag-2 Correlation Test:');
      console.log(`  Correlation coefficient: ${correlation.toFixed(6)}`);

      expect(Math.abs(correlation)).toBeLessThan(0.1);
    });
  });
});

describe('Extended Entropy Quality Tests (10000 samples)', () => {
  let largeSampleSet: RawEntropyResult[];
  let largeHexStrings: string[];
  let largeNumericValues: number[];

  beforeAll(async () => {
    console.log('\nGenerating 10000 entropy samples for extended testing...');
    largeSampleSet = await generateEntropySamples(10000);
    largeHexStrings = samplesToHexStrings(largeSampleSet);
    largeNumericValues = samplesToNumericValues(largeSampleSet);
    console.log(`Generated ${largeSampleSet.length} samples`);
  }, 600000); // 10 minute timeout for large sample generation

  it('passes NIST tests with 10000 samples', () => {
    const results = runNISTTests(largeHexStrings);
    
    console.log('\nExtended NIST Test Results (10000 samples):');
    console.log(`  Overall passed: ${results.passed}`);
    console.log(`  Overall p-value: ${results.pValue.toFixed(6)}`);
    console.log(`  Total bits: ${results.totalBits}`);

    expect(results.passed).toBe(true);
    expect(results.pValue).toBeGreaterThan(0.01);
  });

  it('has uniform distribution with 10000 samples', () => {
    const chiSquare = calculateChiSquare(largeNumericValues, 16);
    
    console.log('\nExtended Chi-Square Test (10000 samples):');
    console.log(`  P-value: ${chiSquare.pValue.toFixed(6)}`);
    console.log(`  Chi-square: ${chiSquare.chiSquare.toFixed(4)}`);

    expect(chiSquare.pValue).toBeGreaterThan(0.01);
  });

  it('maintains high entropy with 10000 samples', () => {
    const result = estimateEntropy(largeHexStrings);
    
    console.log('\nExtended Entropy Estimation (10000 samples):');
    console.log(`  Entropy ratio: ${(result.entropyRatio * 100).toFixed(2)}%`);

    expect(result.entropyRatio).toBeGreaterThanOrEqual(0.95);
  });
});
